version: '3.1'

services:

  pgsql:
    image: postgres:15.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: unimipgsql
    volumes:
      - ./data:/var/lib/postgresql/data

  httpd:
    image: pg-php8.2.6-apache
    build:
      dockerfile: pg-php8.2.6-apache.Dockerfile
    restart: always
    ports: 
      - 8082:80
    volumes:
      - ./../Sito:/var/www/html